name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide details about what you'd like to see.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A clear and concise description of the feature request
      placeholder: Briefly describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the problem or pain point...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this feature work?
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other solutions have you considered?
      placeholder: Describe alternative solutions...

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Important for my use case
        - Critical - Blocking current work
    validations:
      required: true

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Willingness
      options:
        - label: I would be willing to implement this feature
        - label: I would be willing to help test this feature
        - label: I would be willing to help document this feature

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, mockups, or examples
      placeholder: Add any other context, screenshots, or examples...
